.circleci/config.yml
package.json

Setup circleci for CI

---

.eslintrc.json
package.json

Setup husky and eslint (Issue #3)

---

.eslintrc.json
package.json
server/.babelrc
server/package.json
server/src/index.js

Add babel to server-side for ES6 features

---

client/public/index.html

Add bulma.css in index.html file and remove unneeded comments
from the file.
Complete #15

Add bulma.css as central theme

---

package.json
server/package.json
server/src/Sockets/events.js
server/src/Sockets/socket.js
server/src/configs/config.js
server/src/index.js
server/src/tests/socket.test.js

Sets up sockets and provides functions on the server side for implementing messaging.
- complete the functions to handle all socket events.
issue: #24

[WIP] Feat: Add messaging functionality with sockets.

---

package.json
server/src/Constants/constants.js
server/src/Controller/Channel/ChannelController.js
server/src/Controller/Channel/routes.js
server/src/Controller/Message/MessageController.js
server/src/Controller/Message/routes.js
server/src/Controller/User/UserController.js
server/src/Controller/Workspace/WorkspaceController.js
server/src/Controller/Workspace/routes.js
server/src/Model/Channel/ChannelSchema.js
server/src/Model/Message/MessageSchema.js
server/src/Model/User/UserSchema.js
server/src/Model/WorkSpace/WorkspaceSchema.js
server/src/Model/index.js
server/src/Repositories/genericRepository.js
server/src/libs/routes/errorHandler.js
server/src/router.js

Created endpoints for the channel, message and workspace module #18

Feat: Basic Endpoints (CRUD)

---

client/src/components/Sidebar/Sidebar.js
client/src/components/Sidebar/tests/Sidebar.test.js

Add Sidebar component that can take width as a prop and set
CSS accordingly.
Refer #19

style: Add Sidebar component

---

client/src/components/SidebarList/SidebarList.css
client/src/components/SidebarList/SidebarList.js
client/src/components/SidebarList/tests/SidebarList.test.js

Display a list of the item passed in the sidebar. Has heading, action,
list options to customize.
Refer #19

style: Add SidebarList component

---

client/package.json
client/src/components/InputField/InputField.js
client/src/components/NotFound/NotFound.js
client/src/components/SmallContainer/SmallContainer.js
client/src/components/index.js
client/src/constants/constants.js
client/src/containers/SignIn/SignIn.js
client/src/containers/SignIn/tests/SignIn.test.js
client/src/containers/SignUp/Schema.js
client/src/containers/SignUp/SignUp.css
client/src/containers/SignUp/SignUp.js
client/src/containers/SignUp/tests/SignUp.test.js
client/src/containers/index.js
client/src/index.js
client/src/libs/handleInputEvents.js
client/src/libs/utils.js
client/src/libs/validate.js

Add SignUp and Not Found Page #28

Add SignUp and Not Found page

---

client/public/index.html
client/src/containers/Workspaces/Workspaces.js
client/src/containers/index.js
client/src/index.js

Adds the basic frame for displaying workspace, both owned and joined.

feat(UI): Add Workspaces listing dashboard basic UI

---

server/package.json
server/src/tests/testDbSetup.js
server/src/tests/user.test.js

Adds tests for functions in userController which are used by API endpoints.
issue: #14

[WIP] Test: Add tests for user controller api functions

---

client/src/index.js
client/src/routes/AuthRoute/AuthRoute.js
client/src/routes/PrivateRoute/PrivateRoute.js
client/src/routes/index.js

Add Private and Auth Routes

---

server/src/Controller/Channel/ChannelController.js
server/src/Controller/Channel/routes.js
server/src/Controller/Message/MessageController.js
server/src/Controller/Message/routes.js
server/src/Controller/Workspace/WorkspaceController.js
server/src/Controller/Workspace/routes.js
server/src/Repositories/genericRepository.js

Modify getAll endpoints

---

client/src/hooks/useFetch.js

Adds Custom hook for data fetching.
Updates Workspaces page to use useFetch hook.

Custom hook for data fetching

---

package.json

Adds React dependency to root package.json

---

client/package.json
client/src/components/InputField/InputField.js
client/src/containers/SignIn/utils.js
client/src/containers/Workspaces/AddWorkspace.js
client/src/containers/Workspaces/AddWorkspaceSchema.js
client/src/containers/Workspaces/Workspaces.js

It adds a modal component with basic UI in Workspaces container and then integrates it into `Workspaces.js`.

feat(UI): add AddWorkspaceModal component

---

client/src/components/index.js
client/src/containers/Thread/Thread.css
client/src/containers/Thread/Thread.js

Add CSS/JS fix to keep message box form at the bottom. The solution looks like this:

feat(bottom-textarea): Keep textarea at bottom

---

client/src/constants/constants.js
client/src/containers/SignIn/SignIn.js
client/src/containers/SignIn/utils.js
client/src/containers/SignUp/utils.js
client/src/containers/Workspaces/Workspaces.js
server/src/tests/user.test.js

Feat: Add real workspaces data

---

server/src/Constants/constants.js
server/src/Controller/Channel/ChannelController.js
server/src/Controller/Channel/routes.js
server/src/Controller/Workspace/WorkspaceController.js
server/src/Controller/Workspace/routes.js
server/src/Controller/utils.js
server/src/Repositories/genericRepository.js
server/src/tests/channel.test.js
server/src/tests/workspace.test.js

feat: add and delete members from channel and workspace

---

client/src/containers/Workspace/Workspace.js
client/src/containers/Workspace/utils.js
server/src/Controller/Message/MessageController.js

Fixes a bug where user conversations where loading between different workspaces.

Fix(socket): Add check for workspace when loading a conversation

---

server/src/Constants/constants.js
server/src/Controller/Channel/ChannelController.js
server/src/Controller/Workspace/WorkspaceController.js
server/src/Controller/utils.js

fix(addMember): check if member already exists

---

client/.env.development
client/.env.production
client/src/containers/Workspace/Workspace.js
client/src/containers/Workspace/utils.js

Adds env variable for socket endpoint in lieu of hardcoded values.

Fix(socket-ev): add env variables for socket endpoint

---

client/package.json
client/public/index.html
client/src/components/ChannelHeader/ChannelHeader.js
client/src/components/Container/Container.js
client/src/components/Form/Form.js
client/src/components/SidebarList/SidebarList.js
client/src/components/index.js
client/src/constants/constants.js
client/src/containers/AddChannel/AddChannel.js
client/src/containers/AddChannel/AddChannelModal.js
client/src/containers/ChannelMembers/AddMember.css
client/src/containers/ChannelMembers/AddMember.js
client/src/containers/ChannelMembers/ChannelMembers.js
client/src/containers/SignUp/SignUp.js
client/src/containers/Workspace/Workspace.css
client/src/containers/Workspace/Workspace.js
client/src/containers/Workspace/utils.js
client/src/containers/Workspaces/Workspaces.js
client/src/containers/index.js
client/src/index.js
server/src/configs/config.js

Channel Features

---

client/_redirects
client/yarn.lock
server/yarn.lock

Add yarn.lock files that are required for server deployment.
Add `_redirects` file that handles errors on reloading internal pages.
Fixes #93

chore: Add yarn.lock files and netlify _redirects

---

client/package.json
client/src/containers/SignIn/utils.js
client/src/containers/SignUp/utils.js
client/src/libs/axios.js
client/yarn.lock

feat: add toast for showing errors

---

client/_redirects
client/package.json
client/src/components/NavBar/NavBar.js
client/src/components/SidebarList/SidebarList.js
client/src/containers/Workspace/Workspace.js
client/src/containers/Workspaces/AddWorkspace.js
client/src/containers/Workspaces/Workspaces.js
client/yarn.lock

Use workspace modal form and create a new workspace. Upon success
redirect to workspace page.
Fix eslint issues in components that affect tests.
Refer #86

feat(workpace): Add workspace modal form works

---

client/src/components/ChannelHeader/ChannelHeader.js
client/src/components/SidebarList/SidebarList.js
client/src/containers/ChannelMembers/ChannelMembers.js
client/src/containers/Workspace/Workspace.js
client/src/hooks/useFetch.js
client/src/libs/axios.js
client/yarn.lock

1. Refresh all components on update issue #93 
2. Refresh channel list on create new channel 
3. Fix join channel and leave channel issue #104

Channel Bug Fixes

---

client/package.json
client/src/containers/Workspace/utils.js
client/yarn.lock

fix(messageTime): format time in human readable fromat

---

client/src/constants/constants.js
client/src/containers/Workspace/Workspace.js
server/src/Sockets/events.js
server/src/Sockets/socket.js

Adds real-time typing indicator in group and user chats.
issue: #81

Feat (Typing-indicator): Add real time typing indicator to chats.

---

client/src/components/ThreadForm/ThreadForm.js
client/src/containers/Workspace/Workspace.js

Disables the input for a channel if the user is not a member of it. But does not work in real time.
Issue: #90

 Feat(input-disable): Add disabling of input when the user is a not a member

---

client/src/containers/Workspaces/Workspaces.js

feat: add logout functionality

---

client/src/containers/Profile/utils.js
server/package.json
server/src/Controller/User/UserController.js
server/src/Model/User/UserSchema.js
server/yarn.lock

feat(avatar): add avatar in schema

---

client/src/components/Form/Form.js

feat(avatar): add avatar in view profile

---

client/src/components/ChannelNotification/ChannelNotification.js
client/src/components/index.js
client/src/constants/constants.js
client/src/containers/ChannelMembers/ChannelMembers.js
client/src/containers/Workspace/Workspace.js
server/src/Sockets/events.js
server/src/Sockets/socket.js

Shows notifications when a user leaves/is kicked from a channel, or joins/ is added to a channel. Also changes the state of members in a channel in real-time.
issues: #104 #121

 Feat(realtime-notifications): Add notifications for leaving and joining channel

---

client/src/components/SideTab/SideTab.css
client/src/components/SideTab/SideTab.js
client/src/containers/Workspace/Workspace.js

Adds functionality for UI where a channel is boldened if it receives new messages.

Feat(unread-ui): Add unread channels functionality in UI

---

server/package.json
server/src/Constants/constants.js
server/src/Controller/Invitation/InvitationController.js
server/src/Controller/Invitation/routes.js
server/src/Controller/Invitation/utils.js
server/src/Controller/User/UserController.js
server/src/libs/emails/email.js
server/yarn.lock

The invitation can be approved from client-side API as well as serverside
function. The invitation is accepted when the user signs up.
Refer #86

feat(invite): Invitations are accepted at signup

---

client/src/containers/AddChannel/AddChannelModal.js
client/src/containers/AddUser/AddUser.js
client/src/containers/AddUser/AddUserModal.js
client/src/containers/Workspace/Workspace.js
server/src/Constants/constants.js
server/src/Controller/Channel/ChannelController.js
server/src/Controller/Invitation/InvitationController.js
server/src/Controller/Invitation/utils.js

Fixes Add Channel and Add User UI

---

client/src/containers/Workspace/Workspace.css
client/src/index.css

Fixed the look of typing indicator.

 Fix(ui): typing indicator display

---

client/src/containers/Welcome/Welcome.js
client/src/containers/Workspace/Workspace.css

Fix content overflow issue on a mobile device.
Fix variable image width issue on smaller screens

[WIP]: style: Minor Design Changes
